Add Github actions
lazulit3/sea_skipper pull request #6
Opened 2023-06-01 15:42 UTC by Jean-BaptisteC

Fixed #1
Test failed about server, any idea how to fix ?

2023-06-01 21:35 UTC, lazulit3 commented
> Fixed #1 Test failed about server, any idea how to fix ?

2023-06-02 03:51 UTC, lazulit3 reviewed
Thanks for adding these. Only two notes apart from the database service discussed earlier.

If you're willing, this could be enhanced by splitting the lint/clippy, formatting, and test steps into separate jobs. That way if one of those fails it will not halt the run of the others.

(For example, if there was a PR where the clippy lint and tests would pass but the format step would not, the current setup would fail on the format issues before the tests ever get run.)

2023-06-02 03:51 UTC, lazulit3 commented on .github/workflows/main.yml
> +      run: cargo clippy --fix
I don't think `--fix` will have any effect when run in CI here because changes made by `--fix` will not be saved. So `--fix` should be removed.

2023-06-02 03:51 UTC, lazulit3 commented on .github/workflows/main.yml
> +      run: cargo build --verbose
I believe the `Build` step is redundant to the other steps, so this step could be removed. (Since the other steps will fail if the crate is failing to build, a `cargo build` is not explicitly necessary.)

2023-06-02 17:50 UTC, Jean-BaptisteC commented
I have create separate tasks in separate jobs, i understand we need env var to give name container in tests but i don't understand where specify this var.

2023-06-03 16:48 UTC, lazulit3 reviewed
> I have create separate tasks in separate jobs

Thanks! I can [see](https://github.com/Jean-BaptisteC/sea_skipper/actions/runs/5157938610/jobs/9290991710) that the lint and formatting jobs are succeeding even though the tests are failing, so this is a great enhancement.

> i understand we need env var to give name container in tests but i don't understand where specify this var.

Oh, I'm looking again and I think I may have given you an incorrect suggestion. I think I confused the two different approaches described @ https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers#running-jobs-directly-on-the-runner-machine:
- Running jobs in containers
- Running jobs directly on the runner machine

The difference is subtle haha.

I think in this case what you're doing is the "directly on the runner machine type", so I may have been wrong when I said we had to specify the database host (`SEA_SKIPPER_AXUM_EXAMPLE_DB__DATABASE_HOST` as `postgres`). In this case it should be fine to let `axum_example` use its default `db:hostname:` config of `127.0.0.1` (localhost) because GitHub Actions should bind the port there.

I'll add some specific suggestions below and if they don't solve the problem let me know-- I can do some testing on my side to get to the bottom of this if not.

2023-06-03 16:48 UTC, lazulit3 commented on .github/workflows/main.yml
> +          POSTGRES_BD: sea_skipper_axum_example
```suggestion
```
We can remove `POSTGRES_BD`, looks like a typo'd duplicate of `POSTGRES_DB` which is specified above.

2023-06-03 16:48 UTC, lazulit3 commented on .github/workflows/main.yml
> +          SEA_SKIPPER_AXUM_EXAMPLE_DB__DATABASE_HOST: postgres
```suggestion
```
Let's remove this too for two reasons:
- We may not actually need to use `postgres` for the database hostname if this is using the "running jobs directly on the runner machine" approach, because [the config](https://github.com/lazulit3/sea_skipper/blob/f0523f1e0c07d74b2351b5411ba0197c4cd57672/examples/axum_example/config.yml#L5) defaults to `127.0.0.1` for this (which I think is correct).
- If we did need this env var, it would need to be specified where the test is run and not on the database service ([like in this example](https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers#running-jobs-directly-on-the-runner-machine)), but let's try it without first.

2023-06-03 16:48 UTC, lazulit3 commented on .github/workflows/main.yml
> +          - 5433:5433
I think the real issue may be here: Postgres listens on `5432` by default, but this is binding the container's port 5433 to the runner on 5433.

( I used `5433` in `axum_example`'s config to avoid conflicting with another DB service I have in localdev on my workstation for another project.)

Let's try binding the container port 5432 to the runner on 5433, I think that will do the trick.
```suggestion
        ports:
          - 5433:5432
```

2023-06-03 18:20 UTC, Jean-BaptisteC commented
Tests workflow works fine, thanks for help :)

2023-06-03 18:36 UTC, lazulit3 approved these changes
@Jean-BaptisteC Great work! I am going to merge this in a bit, but I'll also spawn a few more issues for CI-related enhancements in case you're interested in taking this further. :)

Thanks!

2023-06-03 18:48 UTC, lazulit3 requested changes
@Jean-BaptisteC Sorry, I just noticed one issue:

It looks like the `cargo fmt --check -v` is not checking all of the crate's files. The current output is:

https://github.com/Jean-BaptisteC/sea_skipper/actions/runs/5165020396/jobs/9304280532#step:3:1

However, if we adjust to `cargo fmt -- --check -v` I think it will check the other files too, based on the example here:
https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server

2023-06-03 18:53 UTC, Jean-BaptisteC commented
Done

2023-06-03 19:03 UTC, lazulit3 approved these changes
Looks great, thanks!

I opened a few low priority issues with some potential follow-up enhancements; just having CI at all is a big improvement, but these will be here in case you want to do more work with GitHub actions:
- https://github.com/lazulit3/sea_skipper/issues/8
- https://github.com/lazulit3/sea_skipper/issues/10
- https://github.com/lazulit3/sea_skipper/issues/9
- https://github.com/lazulit3/sea_skipper/issues/11

2023-06-03 19:06 UTC, merged